# numbers=[1,2,3,4,5]

# result=list(map(lambda x:x*x,numbers))

# print(result)


# I=[1,2,3,4,5]

# square=list(map(lambda x:x**x,I))
# print(square)


# I=[5,10,15]
# add=list(map(lambda x:x+10,I))
# print(add)

# names=["satwik","virat","rajat"]
# upper=list(map(lambda x:x.upper(),names))
# print(upper)

# names=["apple","cat","elephant"]
# result=list(map(lambda x:len(x),names))
# print(result)

def fun(x:)
